name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm first so later steps (including caching) can see it
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            apps/**/pnpm-lock.yaml

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm exec prettier . -c

      - name: Typecheck (web)
        run: pnpm --filter web exec tsc --noEmit

      - name: Test
        run: pnpm vitest run
